### ISSUE TITLE
HipKittens MXFP8 support breaks ROCm 7.0 source build on gfx950

### ISSUE THREAD

**Issue by XinyuJiangCMU** [ROCm/TransformerEngine#653]
Building current `dev` from source fails on **ROCm 7.0.0 / gfx950 (MI355X)**.

The same environment builds `dev` cleanly from a checkout dated 2026-06-21 or earlier, and current `dev` builds fine on ROCm 7.2 — so this is a ROCm 7.0 regression. It appears to start at the "HipKittens MXFP8 GEMM Support" change (commit `6dd7bcb`).

## Environment
- gfx950 (MI355X), ROCm 7.0.0
- `pip install . --no-build-isolation`, `USE_ROCM=ON`

## Two failures

**1. Default build (`USE_HIPKITTENS_GEMM=ON`)** — HipKittens fails in ROCm 7.0 backend codegen:
```
gemm/kittens/mxfp8_gemm.cpp:59:6: error: illegal VGPR to SGPR copy
fatal error: error in backend: Not supported instr: ...
```

**2. With HipKittens off (`-DUSE_HIPKITTENS_GEMM=OFF`)** — the fallback path doesn't compile:
```
gemm/rocm_gemm.cu: error: use of undeclared identifier 's'
```
`hipStream_t s` is declared only inside the HipKittens `#ifdef` block but is still used in the `#else` fallback, so disabling HipKittens leaves `s` undefined.

## Repro
```
git clone --recursive -b dev https://github.com/ROCm/TransformerEngine
cd TransformerEngine
NVTE_FUSED_ATTN=0 pip install . --no-build-isolation -v                                   # failure 1
NVTE_CMAKE_EXTRA_ARGS="-DUSE_HIPKITTENS_GEMM=OFF" NVTE_FUSED_ATTN=0 pip install . --no-build-isolation -v   # failure 2
```

## Ask
Could you please restore a working source build path for ROCm 7.0 / gfx950?

At minimum, `-DUSE_HIPKITTENS_GEMM=OFF` should leave a buildable fallback path. If HipKittens requires ROCm 7.2, it would also be helpful to avoid enabling it by default on ROCm 7.0.

## Workaround
Pin `dev` to a commit from 2026-06-21 or earlier, or build on ROCm 7.2.

**Comment by wenchenvincent** [comment]
@XinyuJiangCMU @lucbruni-amd  This issue should be fixed in the latest dev now. Could you try it out?

**Comment by JessicaJiang-123** [comment]
> [@XinyuJiangCMU](https://github.com/XinyuJiangCMU) [@lucbruni-amd](https://github.com/lucbruni-amd) This issue should be fixed in the latest dev now. Could you try it out?

The build succeeds now. Thanks for the fix!
cc @XinyuJiangCMU
